const Images = {
  partlyCloudyDay: require("./cloudy.gif"),
  partlyCloudyNight: require("./cloudy-night.gif"),
  cloudy: require("./clouds.gif"),
  drizzle: require("./drizzle.gif"),
  foggy: require("./foggy.gif"),
  clearNight: require("./night.gif"),
  rain: require("./rain.gif"),
  snow: require("./snow.gif"),
  storm: require("./storm.gif"),
  clearDay: require("./sun.gif"),
  partlyCloudyDayStatic: require("./cloudy.svg"),
  partlyCloudyNightStatic: require("./cloudy-night.svg"),
  cloudyStatic: require("./clouds.svg"),
  drizzleStatic: require("./drizzle.svg"),
  foggyStatic: require("./foggy.svg"),
  clearNightStatic: require("./night.svg"),
  rainStatic: require("./rain.svg"),
  snowStatic: require("./snow.svg"),
  stormStatic: require("./storm.svg"),
  clearDayStatic: require("./sun.svg"),
};
export default Images;
